name: PR Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: pr-test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-test:
    if: (github.repository == 'sgl-project/SpecForge' || github.event_name == 'pull_request') &&
        github.event.pull_request.draft == false
    runs-on: [self-hosted]
    container:
      image: frankleeeee/specforge:ci
      options: --gpus all --shm-size=2g --rm -v /dev/shm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore cache
        run: |
          if [ -d /github/home/sf ] && [ ! -z "$(ls -A /github/home/sf/)" ]; then
            cp -p -r /github/home/sf/* ./
          fi

      - name: Install dependencies
        shell: bash
        run: |
          which uv
          uv venv sf -p 3.11
          source sf/bin/activate
          uv pip install -v --system --break-system-packages . --prerelease=allow
          which python
          python -c "import specforge"
