name: PR Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: pr-test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-test:
    if: (github.repository == 'sgl-project/SpecForge' || github.event_name == 'pull_request') &&
        github.event.pull_request.draft == false
    runs-on: [self-hosted]
    container:
      image: lmsysorg/sglang:dev
      options: --gpus all --shm-size=2g --rm -v /dev/shm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/
          key: ${{ runner.os }}-specforge
          restore-keys: |
            ${{ runner.os }}-specforge

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Run test
        timeout-minutes: 30
        run: |
          python -m unittest discover -s ./tests -p "test_*.py" -v
